# Generated by Django 4.2 on 2025-11-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='datasets/')),
                ('original_filename', models.CharField(max_length=255)),
                ('summary_json', models.TextField(blank=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
    ]
